### ISSUE TITLE
About the subdivision algorithm running natively on Linux

### ISSUE THREAD

**Issue by chicortiz** [Gages/verse_apps#1]
Hello Warren!

First of all, congratulations for the initiative.

If possible I would like to know why you are trying to put LoqAirou inside a browser if LoqAirou is, in a sense, a browser itself?

Would't it be more elegant if you center your efforts to compile the LoqAirou version that is hosted on Eskil's website "Quelsolaar.com" on Linux?

Please don't get me wrong. I say this in the best sense. I already tried to make this work myself many many times but failed miserably. I simply don't have the complete set of skills to complete the task and no one is willing to help me. I tried many years, on many different institutions, and nobody gave it a damn. 
If you have some time to give me instructions on that direction I'm really willing to work hard on that front. My mindset has a lot of trouble interpreting the source code. I have more ability working with proportions.

I insist on this because the source code hosted on Quelsolaar (for Windows) has the subdivision algorithm (which is reaaally beautiful) already implemented, which the Universe Project trunk does not have. It would be a victory to have it running natively on Linux instead of using Wine. ;)

Thank you very much for your time,

Ortiz

**Comment by Gages** [comment]
Hello! Thanks for your interest.

I am interested in running LoqAirou in a web browser so that it is more accessible for non-technical users without an installation step. For example, a free model sharing site might wish to embed a 3D model editor so that people can quickly edit and share changes to models.

Regarding prioritising platforms, I agree that Linux is fundamental for development, and it makes sense to prioritise that over a web version. So far I have been able to build the code on Linux, and cross compiling for Windows from Linux. My first goal is to make available some binaries that are easily run on Linux and Windows, so that people who find this repository can immediately see the state of the project.

Regarding the subdivision algorithm - it sounds like you have more familiarity with the source code than I do! The original source of the project was this link for [Quel Solaar verse applications WIN32](http://quelsolaar.com/files/verse_apps.zip), which I have been able to build and run natively for Linux. So I think your request on that front has already been met! [(Check this directory?)](https://github.com/Gages/verse_apps/tree/master/source/loq_airou) Otherwise, can you direct me with a URL to a specific version of the source code? Note that only the verse library and server was taken from the blender git repository, not the LoqAirou source - this was taken from QuelSolaar.com.

I would really like to have your help and feedback! My instructions would be, see if you can download and build the program on Linux already! If you get stuck, please write up your criticisms, notes or problems and I'll update the README.md file to help others.

Note that at this stage I haven't done any development or testing of the original source code, but I have been able to run the program on Linux natively.

**Comment by chicortiz** [comment]
O my god! Looks like you already succeed Warren! 

I'm on Ubuntu right now, if you could provide me the binary or instructions to build it, I can test it for you to see if the subdivision algorithm is behaving the same way on Linux that is on Windows.

Did you saw that article of Eskil for the proposal of this variation of the Catmull Clark Algorithm?

Thank you very much for you quick reply.

**Comment by Gages** [comment]
At the moment the only instructions are the README.md file. I will write a more thorough step-by-step set of instructions for you soon. I have not seen that article.

**Comment by Gages** [comment]
[I have written a "tutorial" for Ubuntu 16.04.3](https://github.com/Gages/verse_apps/wiki/Detailed-Build-Instructions:-Ubuntu-16.04)

At the moment I can tell you 100% that the program is not behaving the same way on Linux that it is on Windows. But if you can follow the guide and build the program, that is still useful information. You could a also try pointing Loq Airou at a different verse_server binary if you already have one available.

**Comment by Gages** [comment]
Following up on the point you raised, I have updated the README to change the "First priority" from porting to the browser, to running correctly on Linux.

**Comment by chicortiz** [comment]
Hello Warren. Thank you so much for your replies.

The article that Steenberg wrote to EUROGRAPHICS 2001 can be found here:

http://quelsolaar.com/technology/CRoCCLSS.pdf

I also have a backup of this article myself. I think the beutiful thing about Steenberg's approach is that he adds level of detail to the Catmull Clark algorithm that works in real time inside the modeling tool "LoqAirou" version 1.

(Observation: Steenberg is also working on version two of LoqAirou at the moment, but this feature was not yet reimplemented, from what I know).

YouTube links to version 2 of LoqAirou in action (Timelapses):

1) https://www.youtube.com/watch?v=4aap0BUlocc

2) https://www.youtube.com/watch?v=phiaC8eD8Xw

Another important thing I remembered: The original binaries from the Uni-Verse consortium (circa of 2007) actually have the subdivision surface algorithm implemented, BUT it does not work in real time like the version from Quelsolaar's binaries (http://quelsolaar.com/files/verse_apps.zip). Inside the Uni-verse package version you need to switch between geometry nodes to see that in action. I belive that this was a solicitation from the Blender 3D guys (part of the Uni-Verse consortium) to make Blender work better with LoqAirou in the second release of the Uni-Verse package. But I can be wrong about the existence of this solicitation, Brecht Van Lommel can say if it existed or not.

I'm on Ubuntu 16.04. I will try your manual later on ;)

Thank you very much again.
